let myName= prompt('enter your name')
let lastName = prompt(' enter your last name')
let age = prompt(' enter your age')
let kokantination = prompt(' enter you conkatination level')
let profession = prompt(' what is your profession')
console.log(`My name is ${myName} ${lastName} and my age is ${age}, my level of coc is ${kokantination} and I am ${profession} `)